services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: event_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - event_network

  api_gateway_service:
    build: ./api_gateway_service
    container_name: event_api_gateway
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    networks:
      - event_network
    restart: unless-stopped

  critical_alert_service:
    build: ./critical_alert_service
    container_name: critical_alert_service
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      API_GATEWAY_HOST: api_gateway_service   # важно: имя сервиса, а не контейнера
      API_GATEWAY_PORT: 8000
      RUN_API_TESTS: "true"
    depends_on:
      - rabbitmq
      - api_gateway_service
    networks:
      - event_network
    restart: unless-stopped

volumes:
  rabbitmq_data:

networks:
  event_network:
    driver: bridge