services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: eventbridge_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - eventbridge-net

  orchestrator:
    build:
      context: ./orchestrator-service
    container_name: eventbridge_orchestrator
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
    networks:
      - eventbridge-net

  api_gateway:
    build:
      context: ./api_gateway_service
    container_name: eventbridge_api_gateway
    ports:
      - "8000:8000"
    depends_on:
      orchestrator:
        condition: service_started
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    networks:
      - eventbridge-net

  email_service:
    build:
      context: ./email-service
    container_name: eventbridge_email_service
    depends_on:
      rabbitmq:
        condition: service_healthy
      orchestrator:
        condition: service_started
    restart: on-failure
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
    networks:
      - eventbridge-net

  redis:
    image: redis:7-alpine
    container_name: eventbridge_redis
    ports:
      - "6379:6379"
    networks:
      - eventbridge-net

  console_monitor:
    build:
      context: ./console_monitor_service
    container_name: eventbridge_console_monitor
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      REDIS_HOST: redis
      REDIS_PORT: 6379
      STATS_INTERVAL: "10"
      RECONNECT_DELAY: "5"
      MAX_RECONNECT_ATTEMPTS: "0"
    networks:
      - eventbridge-net

  # DATABASE SERVICE
  database_service:
    build:
      context: ./database_service
    container_name: eventbridge_database_service
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: event_bridge

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest

      QUEUE_NAME: db_log_queue
    networks:
      - eventbridge-net

volumes:
  postgres_data:

networks:
  eventbridge-net:
    driver: bridge
