services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: eventbridge_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - eventbridge-net

  orchestrator:
    build:
      context: ./orchestrator-service
    container_name: eventbridge_orchestrator
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    networks:
      - eventbridge-net

  api_gateway:
    build:
      context: ./api_gateway_service
    container_name: eventbridge_api_gateway
    ports:
      - "8000:8000"
    depends_on:
      orchestrator:
        condition: service_started
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    networks:
      - eventbridge-net

  redis:
    image: redis:7-alpine
    container_name: eventbridge_redis
    ports:
      - "6379:6379"
    networks:
      - eventbridge-net

  # 
  critical_alert_service:
    build:
      context: ./critical_alert_service
    container_name: eventbridge_critical_alert
    depends_on:
      orchestrator:
        condition: service_started
      api_gateway:
        condition: service_started
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      QUEUE_NAME: critical_alert_queue
      API_GATEWAY_HOST: api_gateway
      API_GATEWAY_PORT: 8000
      RUN_API_TESTS: "true"
    networks:
      - eventbridge-net
    restart: unless-stopped
  # 

networks:
  eventbridge-net:
    driver: bridge